version: '3.8'

services:
  api:
    image: nishify_studio_api:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - ELASTIC_URL=${ELASTIC_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    restart: always

  ui:
    image: nishify_studio_ui:latest
    ports:
      - "4001:4001"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000/api
    restart: always
