import fs from 'fs';
import path from 'path';
import { parseSchema } from 'json-schema-to-zod';

const SYSTEM_CONFIG_DIR = path.resolve(process.cwd(), '../system-configuration');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/types/resumeBuilder/resume.ts');

function readJsonSchema(filePath: string) {
  const content = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(content);
}

// 1. Read all the atomic schemas
const profileSchema = readJsonSchema(path.join(SYSTEM_CONFIG_DIR, 'common/profile.schema.json'));
const metadataSchema = readJsonSchema(path.join(SYSTEM_CONFIG_DIR, 'resumeBuilder/metadata.schema.json'));
const softwareSchema = readJsonSchema(path.join(SYSTEM_CONFIG_DIR, 'industry/software.schema.json'));
const salesSchema = readJsonSchema(path.join(SYSTEM_CONFIG_DIR, 'industry/sales.schema.json'));

// 2. Dynamically construct the "Super Schema"
// This object represents the absolute flattened state that React will use 
// covering ANY combination of industries via the strict __ namespace.
const superSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "ResumeModel",
  type: "object",
  properties: {
    metadata: metadataSchema,
    personalInfo: profileSchema,
    
    // Flatten and inject all industry namespaces here
    ...softwareSchema.properties,
    ...salesSchema.properties,
    
    // Legacy mapping support while we migrate
    summary: { type: "array", items: { type: "string" } },
    skills: { type: "array", items: { type: "object", properties: { category: { type: "string" }, items: { type: "string" } }, required: ["category", "items"] } },
    experience: { type: "array", items: { type: "object", properties: { company: { type: "string" }, role: { type: "string" }, dates: { type: "string" }, points: { type: "array", items: { type: "string" } } }, required: ["company", "role", "dates", "points"] } },
    education: { type: "array", items: { type: "object", properties: { degree: { type: "string" }, institution: { type: "string" }, dates: { type: "string" } }, required: ["degree", "institution", "dates"] } }
  },
  required: ["metadata", "personalInfo", "summary", "skills", "experience", "education"]
};

// 3. Compile the JSON standard Super Schema into runtime Zod
const zodCode = parseSchema(superSchema);

const finalFileContent = `import { z } from 'zod';

/**
 * AUTO-GENERATED SCHEMA FROM system-configuration REGISTRY.
 * DO NOT EDIT MANUALLY.
 * This file is generated by scripts/generate-schemas.ts
 */

export const ResumeModelSchema = ${zodCode};

export type ResumeModel = z.infer<typeof ResumeModelSchema>;
`;

// 4. Write back into the React App architecture
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, finalFileContent);
console.log('✅ Successfully compiled API-First JSON Registry into Zod typings.');
