import fs from 'fs';
import path from 'path';
import { parseSchema } from 'json-schema-to-zod';
import merge from 'lodash.merge';

const LANGUAGE = process.env.VITE_APP_LANGUAGE || 'en';
const CLIENT = process.env.VITE_APP_CLIENT || 'default';

const BASE_DIR = path.resolve(process.cwd(), `../system-configuration/base/${LANGUAGE}`);
const CLIENT_DIR = path.resolve(process.cwd(), `../system-configuration/client_specific/${CLIENT}/${LANGUAGE}`);
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/types/resumeBuilder/resume.ts');

function readJsonSchema(relativePath: string) {
  const baseFile = path.join(BASE_DIR, relativePath);
  const clientFile = path.join(CLIENT_DIR, relativePath);
  
  let baseSchema = {};
  let clientSchema = {};

  if (fs.existsSync(baseFile)) {
    baseSchema = JSON.parse(fs.readFileSync(baseFile, 'utf-8'));
  }
  
  if (CLIENT !== 'default' && fs.existsSync(clientFile)) {
    clientSchema = JSON.parse(fs.readFileSync(clientFile, 'utf-8'));
    console.log(`[SaaS Provider] Applying '${CLIENT}' override logic to ${relativePath}`);
  }

  // Deep merge: Client Schema aggressively overrides Base Schema
  return merge({}, baseSchema, clientSchema);
}

// 1. Read all atomic schemas (merging any client/language overrides dynamically)
const profileSchema = readJsonSchema('common/profile.schema.json');
const metadataSchema = readJsonSchema('resumeBuilder/metadata.schema.json');
const softwareSchema = readJsonSchema('industry/software.schema.json');
const salesSchema = readJsonSchema('industry/sales.schema.json');

// 2. Dynamically construct the "Super Schema"
// This object represents the absolute flattened state that React will use 
// covering ANY combination of industries via the strict __ namespace.
const superSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "ResumeModel",
  type: "object",
  properties: {
    metadata: metadataSchema,
    personalInfo: profileSchema,
    
    // Flatten and inject all industry namespaces here
    ...softwareSchema.properties,
    ...salesSchema.properties,
    
    // Legacy mapping support while we migrate
    summary: { type: "array", items: { type: "string" } },
    skills: { type: "array", items: { type: "object", properties: { category: { type: "string" }, items: { type: "string" } }, required: ["category", "items"] } },
    experience: { type: "array", items: { type: "object", properties: { company: { type: "string" }, role: { type: "string" }, dates: { type: "string" }, points: { type: "array", items: { type: "string" } } }, required: ["company", "role", "dates", "points"] } },
    education: { type: "array", items: { type: "object", properties: { degree: { type: "string" }, institution: { type: "string" }, dates: { type: "string" } }, required: ["degree", "institution", "dates"] } }
  },
  required: ["metadata", "personalInfo", "summary", "skills", "experience", "education"]
};

// 3. Compile the JSON standard Super Schema into runtime Zod
const zodCode = parseSchema(superSchema);

// SKILLON PLATFORM SCHEMAS
const courseSchemaStr = fs.readFileSync(path.resolve(process.cwd(), '../system-configuration/preparation/course.schema.json'), 'utf-8');
const courseSchemaObj = JSON.parse(courseSchemaStr);
const courseZodCode = parseSchema(courseSchemaObj);

const finalFileContent = `import { z } from 'zod';

/**
 * AUTO-GENERATED SCHEMA FROM system-configuration REGISTRY.
 * DO NOT EDIT MANUALLY.
 * This file is generated by scripts/generate-schemas.ts
 */

export const ResumeModelSchema = ${zodCode};
export type ResumeModel = z.infer<typeof ResumeModelSchema>;

export const CourseModelSchema = ${courseZodCode};
export type CourseModel = z.infer<typeof CourseModelSchema>;
`;

// 4. Write back into the React App architecture
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, finalFileContent);
console.log('✅ Successfully compiled API-First JSON Registry into Zod typings.');
