import { z } from 'zod';

/**
 * AUTO-GENERATED SCHEMA FROM system-configuration REGISTRY.
 * DO NOT EDIT MANUALLY.
 * This file is generated by scripts/generate-schemas.ts
 */

export const ResumeModelSchema = z.object({ "metadata": z.object({ "template": z.string(), "theme": z.object({ "primaryColor": z.string().optional(), "secondaryColor": z.string().optional(), "fontFamily": z.string().optional() }).optional() }), "personalInfo": z.object({ "fullName": z.string(), "title": z.string().optional(), "email": z.string().email(), "phone": z.string().optional(), "linkedin": z.string().regex(new RegExp("^https://www\\.linkedin\\.com/in/.+")), "location": z.string().optional() }), "software__summary": z.array(z.string()).optional(), "software__skills": z.array(z.object({ "category": z.string(), "items": z.string() })).optional(), "software__experience": z.array(z.object({ "company": z.string(), "role": z.string(), "dates": z.string(), "points": z.array(z.string()) })).optional(), "software__projects": z.array(z.object({ "name": z.string(), "description": z.string(), "technologies": z.array(z.string()).optional() })).optional(), "sales__summary": z.array(z.string()).optional(), "sales__skills": z.array(z.object({ "category": z.string(), "items": z.string() })).optional(), "sales__experience": z.array(z.object({ "company": z.string(), "role": z.string(), "dates": z.string(), "quota_attainment": z.string().optional(), "points": z.array(z.string()) })).optional(), "summary": z.array(z.string()), "skills": z.array(z.object({ "category": z.string(), "items": z.string() })), "experience": z.array(z.object({ "company": z.string(), "role": z.string(), "dates": z.string(), "points": z.array(z.string()) })), "education": z.array(z.object({ "degree": z.string(), "institution": z.string(), "dates": z.string() })) });

export type ResumeModel = z.infer<typeof ResumeModelSchema>;
